name: firt-action

on: push

jobs:
    tworuns:
        runs-on: ubuntu-latest
        steps:
            - uses: clowdhaus/argo-cd-action/@main
              with:
                  version: 2.3.3
                  command: version
                  options: --client
