name: firt-action

on: push

jobs:
    tworuns:
        runs-on: ubuntu-latest        
        steps:
            
            - uses: clowdhaus/argo-cd-action/@main
              with:
                  version: 2.3.3
                  command: version
                  options: --client
            - name: action with option in single line
              uses: clowdhaus/argo-cd-action/@main
              with:
                version: 2.3.3
                command: version --client

            - name: same action with 2 commands
              uses: clowdhaus/argo-cd-action/@main
              with:
                version: 2.3.3
                command: >
                    version --client ;
                    /opt/hostedtoolcache/argocd/2.3.3/x64/argocd help
                

            
