name: firt-action

on: push

jobs:
    tworuns:
        runs-on: ubuntu-latest
        steps:
            - name: Downloading ArgoCD Ation
              uses: clowdhaus/argo-cd-action/@main
              with:
                version: 2.3.3
                command: version --client
                
            - name: locating argocd and running commands 
              run: |
                echo "Running ArgoCD"
                which argocd
                argocd version --client
                argocd help
                argocd version --client
                






#            - name: same action with 2 commands
#              uses: clowdhaus/argo-cd-action/@main
#              with:
#                version: 2.3.3
#                command: ${{ matrix.commands }}                

            
